myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
]

tasks/urls.py
# tasks/urls.py

from django.urls import path, re_path
from . import views


app_name = 'tasks'

urlpatterns = [


    path('create/', views.task_create, name='task_create'),


    path('', views.task_list, name='task_list'),


    re_path(r'^(?P<pk>\d+)/$', views.task_detail, name='task_detail'),


    re_path(r'^(?P<pk>\d+)/update/$', views.task_update, name='task_update'),


    re_path(r'^(?P<pk>\d+)/delete/$', views.task_delete, name='task_delete'),

]

tasks/models.py
from django.db import models

class Status(models.TextChoices):
    UNSTARTED = 'u', "Ещё не начата"
    ONGOING = 'o', "В процессе"
    FINISHED = 'f', "Закончена"


class Task(models.Model):
    name = models.CharField(verbose_name="Имя задачи", max_length=65, unique=True)
    status = models.CharField(verbose_name="Статус задачи", max_length=1, choices=Status.choices)

    def __str__(self):
        return self.name

tasks/forms.py
#-*- coding:utf-8 -*-
from .models import Task
from django import forms

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = "__all__"

myproject/views.py
from django.http import HttpResponse

def home(request):
    return HttpResponse("http://localhost:8000/tasks")

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Task
from .forms import TaskForm

def task_create(request):
     if request.method == "POST":
         form = TaskForm(request.POST)
         if form.is_valid():
             form.save()
             return redirect(reverse("tasks:task_list"))
     else:
         form = TaskForm()

     return render(request, "tasks/task_form.html", { "form": form, })


def task_list(request):
     tasks = Task.objects.all()
     return render(request, "tasks/task_list.html", { "tasks": tasks,})

def task_detail(request, pk):
     task = get_object_or_404(Task, pk=pk)
     return render(request, "tasks/task_detail.html", { "task": task, })

def task_update(request, pk):
     task_obj = get_object_or_404(Task, pk=pk)
     if request.method == 'POST':
         form = TaskForm(instance=task_obj, data=request.POST)
         if form.is_valid():
             form.save()
             return redirect(reverse("tasks:task_detail", args=[pk,]))
     else:
         form = TaskForm(instance=task_obj)

     return render(request, "tasks/task_form.html", { "form": form, "object": task_obj})

def task_delete(request, pk):
    task_obj = get_object_or_404(Task, pk=pk)
    task_obj.delete()
    return redirect(reverse("tasks:task_list"))

from django.views.generic import ListView, DetailView, \
    CreateView, UpdateView, DeleteView

class TaskListView(ListView):
    model = Task
    context_object_name = 'tasks'

class TaskDetailView(DetailView):
    model = Task

class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')

class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')

class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:task_list')

tasks/templates/tasks/task_confirm_delete.html
<!DOCTYPE html>
<form method="post">{% csrf_token %}
    <p>Вы действительно хотите удалить задачу? "{{ task }}"?</p>
    <input type="submit" value="Confirm" />
</form>

tasks/templates/tasks/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Детали задачи</title>
</head>
<body>
<p> Имя задачи: {{ task.name }} | <a href="{% url 'tasks:task_update' task.id %}">Изменить</a> |
    <a href="{% url 'tasks:task_delete' task.id %}">Удалить</a>
</p>
<p> Стутус задачи: {{ task.get_status_display }} </p>
<p> <a href="{% url 'tasks:task_list' %}">Посмотреть все задачи</a> |
    <a href="{% url 'tasks:task_create'%}">Добавить новую задачу</a>
</p>
</body>
</html>

tasks/templates/tasks/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if object %}Редактировать задачу {% else %} Добавить новую задачу {% endif %}</title>
</head>
<body>
<h3>{% if object %} Редактировать задачу {% else %} Добавить новую задачу {% endif %}</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" class="btn btn-success" value="Добавить"></p>
    </form>
</body>
</html>

tasks/templates/tasks/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список задач</title>
</head>
<body>
<h3>Список задач</h3>
{% for task in tasks %}
    <p>{{ forloop.counter }}. {{ task.name }} - {{ task.get_status_display }}
        (<a href="{% url 'tasks:task_update' task.id %}">Обновить</a> |
        <a href="{% url 'tasks:task_delete' task.id %}">Удалить</a>)
    </p>
{% endfor %}

<p> <a href="{% url 'tasks:task_create' %}"> + Добавить новую задачу</a></p>
</body>
</html>